print ("Tugas Python")
print ()
nama = input("Masukan nama Anda :")
panggilan = input("Masukan Panggilan :")
nim = input("Masukan NIM :")
tglhr = input("Masukan Tanggal Lahir :")
tmlhr = input("Masukan Tempat Lahir :")
tlpn = input ("Masukan Nomer Telepon :")
alamat = input ("Masukan Alamat :")
umur = ("Masukan Umur Anda :")
print ()
print ("Asslamua'laikum")
print ()
print ("Let me introduce my self. my name is",nama,"but you can call me",panggilan,"My NIM is",nim,"I was born in",tmlhr,"and I am",umur,"years old. I am very gold if you want to invite my house in",alamat,". So,don't forget to call me before with the number",tlpn,)
print ()
print ("THANK YOU")

